spring:
  application:
    name: sse_test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: optional:file:.env[.properties]
aws:
  ses:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    send-mail-to: ${AWS_SEND_MAIL_TO}
  region: ${AWS_REGION}